export const templateList = [
  {
    id: 1,
    description: '🚀 A React quick start project template powered by vite.',
    title: 'react-base',
    tags: ['react', 'vite', 'husky', 'eslint', 'eslint-prettier'],
    dependencies: [
      '@types/react',
      '@types/react-dom',
      '@typescript-eslint/eslint-plugin',
      '@typescript-eslint/parser',
      '@vitejs/plugin-react-refresh',
      'eslint',
      'eslint-config-prettier',
      'eslint-plugin-import',
      'eslint-plugin-jsx-a11y',
      'eslint-plugin-prettier',
      'eslint-plugin-react',
      'eslint-plugin-simple-import-sort',
      'lint-staged',
      'npm-run-all',
      'prettier',
      'typescript',
      'vite',
      'husky'
    ],
    category: 'Misc'
  },
  {
    id: 2,
    description: 'Starter Base-React project that includes react-router-dom v6 powered by vite.',
    title: 'react-Base-router-Configs',
    tags: ['react', 'vite', 'react-router-dom'],
    dependencies: [
      'react-router-dom',
      '@types/react',
      '@types/react-dom',
      '@typescript-eslint/eslint-plugin',
      '@typescript-eslint/parser',
      '@vitejs/plugin-react-refresh',
      'eslint',
      'eslint-config-prettier',
      'eslint-plugin-import',
      'eslint-plugin-jsx-a11y',
      'eslint-plugin-prettier',
      'eslint-plugin-react',
      'eslint-plugin-simple-import-sort',
      'lint-staged',
      'npm-run-all',
      'prettier',
      'typescript',
      'vite',
      'husky'
    ],
    category: 'Misc'
  },
  {
    id: 3,
    description:
      "A Quick react starter project template powered by vite with React Testing Library. A testing utility tool that's built to test the actual DOM tree rendered by React on the browser.",
    title: 'react-Base-testing-library',
    tags: ['react', 'vite', 'testing-library'],
    dependencies: [
      '@testing-library/react',
      '@types/react',
      '@types/react-dom',
      '@typescript-eslint/eslint-plugin',
      '@typescript-eslint/parser',
      '@vitejs/plugin-react-refresh',
      'eslint',
      'eslint-config-prettier',
      'eslint-plugin-import',
      'eslint-plugin-jsx-a11y',
      'eslint-plugin-prettier',
      'eslint-plugin-react',
      'eslint-plugin-simple-import-sort',
      'lint-staged',
      'npm-run-all',
      'prettier',
      'typescript',
      'vite',
      'husky'
    ],
    category: 'Misc'
  },
  {
    id: 4,
    description:
      'A Quick react starter project template powered by vite with React Testing Library and Apollo Client, A comprehensive state management library for JavaScript that enables you to manage both local and remote data with GraphQL. Use it to fetch, cache, and modify application data, all while automatically updating your UI.',
    title: 'react-base-testing-library-apollo',
    tags: ['react', 'vite', 'apollo', 'testing-library', 'graphql'],
    dependencies: [
      '@apollo/client',
      '@graphql-tools/mock',
      '@graphql-tools/schema',
      '@testing-library/react',
      'graphql',
      '@testing-library/react',
      '@types/react',
      '@types/react-dom',
      '@typescript-eslint/eslint-plugin',
      '@typescript-eslint/parser',
      '@vitejs/plugin-react-refresh',
      'eslint',
      'eslint-config-prettier',
      'eslint-plugin-import',
      'eslint-plugin-jsx-a11y',
      'eslint-plugin-prettier',
      'eslint-plugin-react',
      'eslint-plugin-simple-import-sort',
      'lint-staged',
      'npm-run-all',
      'prettier',
      'typescript',
      'vite',
      'husky'
    ],
    category: 'Data-fetching'
  },
  {
    id: 5,
    description:
      'A Quick react starter project template powered by vite with React Testing Library and React Query, The missing data-fetching library for React, but in more technical terms, it makes fetching, caching, synchronizing and updating server state in your React applications a breeze',
    title: 'react-base-testing-library-react-query',
    tags: ['react', 'vite', 'testing-library', 'react-query', 'react-hooks', 'react-test-renderer'],
    dependencies: [
      'testing-library/react-hooks',
      'react-query',
      'react-test-renderer',
      'react-router-dom',
      '@types/react',
      '@types/react-dom',
      '@typescript-eslint/eslint-plugin',
      '@typescript-eslint/parser',
      '@vitejs/plugin-react-refresh',
      'eslint',
      'eslint-config-prettier',
      'eslint-plugin-import',
      'eslint-plugin-jsx-a11y',
      'eslint-plugin-prettier',
      'eslint-plugin-react',
      'eslint-plugin-simple-import-sort',
      'lint-staged',
      'npm-run-all',
      'prettier',
      'typescript',
      'vite',
      'husky'
    ],
    category: 'Data-fetching'
  }
];
